"""user auth data

Revision ID: d20484c828f2
Revises: 19db28127c11
Create Date: 2022-09-28 07:57:18.333290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20484c828f2'
down_revision = '19db28127c11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('active', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
