"""added scopes for user

Revision ID: e60f1312488c
Revises: d20484c828f2
Create Date: 2022-09-29 15:25:49.706436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60f1312488c'
down_revision = 'd20484c828f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('scopes_str', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'scopes_str')
    # ### end Alembic commands ###
